### PR TITLE
Removed offer grace period

### LINKED ISSUE #204: Let Offers be edited regardless of grace period
The idea behind having this check was for offers to not be edited after a long period and mislead students. Considering companies can just delete them and recreate the edited version, this makes no sense, so we can just let them have it.

### PR DESCRIPTION
**Pull request by CarlosMealha**
closes #204

### CODE REVIEW

**Comment by imnotteixeira** [comment]
Looks good, try running `npm audit fix` to try to fix the audit problem (make sure you are running with node 14)

**Comment by BrunoRosendo** [comment]
I've tried to fix the audit but nodemailer-express-handlebars hasn't been updated yet (vulnerability in its only dependency). Should we just wait? @imnotteixeira

**Comment by imnotteixeira** [comment]
Let's see if this is solved this week. I pinged the package owner https://github.com/yads/nodemailer-express-handlebars/pull/52#issuecomment-1046219399

Couldn't find an email, and seems like he's not active on twitter, so this is our best shot.

If this isn't solved, we can try bumping our node and npm versions, since in npmv8 we have an `overrides` option to override transitive dependency versions, to solve this.

**Comment by DoStini** [comment]
I don't think the author of that published the most recent update yet

**Comment by BrunoRosendo** [comment]
He updated in GitHub but not yet in npm :/

**Review by BrunoRosendo — APPROVED** [review]

**Pull request merged**
