### PR TITLE
Bump node version to 14.13.1 Current

### LINKED ISSUE #65: Update nodejs versions in Dockerfiles
The node versions we are using in the Dockerfiles seem to be LTS 8. However, the current LTS is 12.14.1.

We should update the app to this LTS, alongside the dockerfiles and any other configurations that need changing.

This is quite pressing as the version mismatch is pretty high.

### PR DESCRIPTION
**Pull request by xRuiAlves**
Closes #65

### CODE REVIEW

**Review by imnotteixeira — CHANGES_REQUESTED** [review]
Update travis.yml to use node_js: 12 (https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions) in order to make it consistent as well

**Comment by xRuiAlves** [comment]
> Update travis.yml to use node_js: 12 (https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions) in order to make it consistent as well

Yeap, missed that. Done :+1:

**Review by imnotteixeira — CHANGES_REQUESTED** [review]
In two weeks nodejs 14 will be the current LTS, let's update now. https://nodejs.org/en/about/releases/

Also, I really want the optional chain operator. 👀

**Comment by imnotteixeira** [comment]
> 
> 
> In two weeks nodejs 14 will be the current LTS, let's update now. https://nodejs.org/en/about/releases/
> 
> Also, I really want the optional chain operator. 👀

Don't forget to update the PR's title :P

**Review by imnotteixeira — APPROVED** [review]

**Pull request merged**
